version: "3"

services:
  app:
    build: .
    container_name: catalog-service-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    volumes:
      - .:/var/www
    depends_on:
      - db
      - redis

  nginx:
    build: .docker/nginx
    container_name: catalog-service-nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: catalog-service-db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root

  redis:
    image: redis:alpine
    container_name: catalog-service-redis
    expose:
      - 6379
